### ISSUE TITLE
Installation of icon

### ISSUE THREAD

**Issue by j-rachit** [halacoglu/sublime-material-icon-pack#2]
How do I install these icons? For reference, I running Sublime Text on Windows 10.

**Comment by halacoglu** [comment]
- For Windows 10, you can just change the shortcut icon on your desktop. Right click on the **Sublime Text shortcut > Properties > Change Icon > Browse...** and choose your desired icon. This is the safe way.
- There is also the permanent way. Download and install [Resource Hacker](http://www.angusj.com/resourcehacker/). Launch Resource Hacker and open **C:\Program Files\Sublime Text 3\sublime_text.exe**. Left click and expand **Icon Group** on the left panel. Right click on **103 : 3081** (With a star, file name may vary) and click on **Replace Icon... > Open file with new icon...** Navigate to the icon folder, choose your desired icon and hit **Replace**. Now save the modified **sublime_text.exe** on your desktop. Backup the original .exe in the installation folder and copy the modified .exe to the installation folder. You're done!
